package com.ygy.model;

import java.io.Serializable;

public class Customer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_name
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_phone
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private String cPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Preference
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private String preference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_id
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private String cId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_name
     *
     * @return the value of customer.c_name
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_name
     *
     * @param cName the value for customer.c_name
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setcName(String cName) {
        this.cName = cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_phone
     *
     * @return the value of customer.c_phone
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_phone
     *
     * @param cPhone the value for customer.c_phone
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Preference
     *
     * @return the value of customer.Preference
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public String getPreference() {
        return preference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Preference
     *
     * @param preference the value for customer.Preference
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setPreference(String preference) {
        this.preference = preference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_id
     *
     * @return the value of customer.c_id
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_id
     *
     * @param cId the value for customer.c_id
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setcId(String cId) {
        this.cId = cId;
    }
}