package com.ygy.model;

import lombok.Data;

@Data
public class Menu implements java.io.Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_id
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.m_name
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private String mName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.weather
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private String weather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Season
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private Integer season;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.hotcold
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private Integer hotcold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_hot
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private Integer menuHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_acid
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private Integer menuAcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_sweet
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private Integer menuSweet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_bitter
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private Integer menuBitter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.resta_id
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private String restaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.imgurl
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.price
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.m_type
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    private String mType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_id
     *
     * @return the value of menu.menu_id
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_id
     *
     * @param menuId the value for menu.menu_id
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.m_name
     *
     * @return the value of menu.m_name
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.m_name
     *
     * @param mName the value for menu.m_name
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setmName(String mName) {
        this.mName = mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.weather
     *
     * @return the value of menu.weather
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.weather
     *
     * @param weather the value for menu.weather
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setWeather(String weather) {
        this.weather = weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Season
     *
     * @return the value of menu.Season
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public Integer getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Season
     *
     * @param season the value for menu.Season
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setSeason(Integer season) {
        this.season = season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.hotcold
     *
     * @return the value of menu.hotcold
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public Integer getHotcold() {
        return hotcold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.hotcold
     *
     * @param hotcold the value for menu.hotcold
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setHotcold(Integer hotcold) {
        this.hotcold = hotcold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_hot
     *
     * @return the value of menu.menu_hot
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public Integer getMenuHot() {
        return menuHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_hot
     *
     * @param menuHot the value for menu.menu_hot
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setMenuHot(Integer menuHot) {
        this.menuHot = menuHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_acid
     *
     * @return the value of menu.menu_acid
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public Integer getMenuAcid() {
        return menuAcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_acid
     *
     * @param menuAcid the value for menu.menu_acid
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setMenuAcid(Integer menuAcid) {
        this.menuAcid = menuAcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_sweet
     *
     * @return the value of menu.menu_sweet
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public Integer getMenuSweet() {
        return menuSweet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_sweet
     *
     * @param menuSweet the value for menu.menu_sweet
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setMenuSweet(Integer menuSweet) {
        this.menuSweet = menuSweet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_bitter
     *
     * @return the value of menu.menu_bitter
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public Integer getMenuBitter() {
        return menuBitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_bitter
     *
     * @param menuBitter the value for menu.menu_bitter
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setMenuBitter(Integer menuBitter) {
        this.menuBitter = menuBitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.resta_id
     *
     * @return the value of menu.resta_id
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public String getRestaId() {
        return restaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.resta_id
     *
     * @param restaId the value for menu.resta_id
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setRestaId(String restaId) {
        this.restaId = restaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.imgurl
     *
     * @return the value of menu.imgurl
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.imgurl
     *
     * @param imgurl the value for menu.imgurl
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.price
     *
     * @return the value of menu.price
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.price
     *
     * @param price the value for menu.price
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.m_type
     *
     * @return the value of menu.m_type
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public String getmType() {
        return mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.m_type
     *
     * @param mType the value for menu.m_type
     *
     * @mbggenerated Sun May 12 11:29:17 CST 2019
     */
    public void setmType(String mType) {
        this.mType = mType;
    }
}