package com.ygy.model;

public class Restaurant implements java.io.Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.r_id
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    private String rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.pass
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    private String pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.address
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.r_Phone
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    private String rPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.time
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.name
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.r_id
     *
     * @return the value of restaurant.r_id
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.r_id
     *
     * @param rId the value for restaurant.r_id
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public void setrId(String rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.pass
     *
     * @return the value of restaurant.pass
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.pass
     *
     * @param pass the value for restaurant.pass
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public void setPass(String pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.address
     *
     * @return the value of restaurant.address
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.address
     *
     * @param address the value for restaurant.address
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.r_Phone
     *
     * @return the value of restaurant.r_Phone
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public String getrPhone() {
        return rPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.r_Phone
     *
     * @param rPhone the value for restaurant.r_Phone
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public void setrPhone(String rPhone) {
        this.rPhone = rPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.time
     *
     * @return the value of restaurant.time
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.time
     *
     * @param time the value for restaurant.time
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.name
     *
     * @return the value of restaurant.name
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.name
     *
     * @param name the value for restaurant.name
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}