package com.ygy.model;

import java.util.Date;

public class Restaurant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.r_id
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private String rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.name
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.address
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Lon
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private Double lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.Lat
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.r_Phone
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private String rPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.r_IsGroupBuy
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private Boolean rIsgroupbuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.AllRating
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private Float allrating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.menu_id
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.BeginTime
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.EndTime
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.r_id
     *
     * @return the value of restaurant.r_id
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.r_id
     *
     * @param rId the value for restaurant.r_id
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setrId(String rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.name
     *
     * @return the value of restaurant.name
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.name
     *
     * @param name the value for restaurant.name
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.address
     *
     * @return the value of restaurant.address
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.address
     *
     * @param address the value for restaurant.address
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Lon
     *
     * @return the value of restaurant.Lon
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Lon
     *
     * @param lon the value for restaurant.Lon
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.Lat
     *
     * @return the value of restaurant.Lat
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.Lat
     *
     * @param lat the value for restaurant.Lat
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.r_Phone
     *
     * @return the value of restaurant.r_Phone
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public String getrPhone() {
        return rPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.r_Phone
     *
     * @param rPhone the value for restaurant.r_Phone
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setrPhone(String rPhone) {
        this.rPhone = rPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.r_IsGroupBuy
     *
     * @return the value of restaurant.r_IsGroupBuy
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public Boolean getrIsgroupbuy() {
        return rIsgroupbuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.r_IsGroupBuy
     *
     * @param rIsgroupbuy the value for restaurant.r_IsGroupBuy
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setrIsgroupbuy(Boolean rIsgroupbuy) {
        this.rIsgroupbuy = rIsgroupbuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.AllRating
     *
     * @return the value of restaurant.AllRating
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public Float getAllrating() {
        return allrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.AllRating
     *
     * @param allrating the value for restaurant.AllRating
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setAllrating(Float allrating) {
        this.allrating = allrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.menu_id
     *
     * @return the value of restaurant.menu_id
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.menu_id
     *
     * @param menuId the value for restaurant.menu_id
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.BeginTime
     *
     * @return the value of restaurant.BeginTime
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.BeginTime
     *
     * @param begintime the value for restaurant.BeginTime
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.EndTime
     *
     * @return the value of restaurant.EndTime
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.EndTime
     *
     * @param endtime the value for restaurant.EndTime
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}