package com.ygy.model;

public class TOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.o_id
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    private String oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.price
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.orderrid
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    private String orderrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.tableid
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    private Integer tableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.mid
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    private String mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.o_id
     *
     * @return the value of t_order.o_id
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.o_id
     *
     * @param oId the value for t_order.o_id
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    public void setoId(String oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.price
     *
     * @return the value of t_order.price
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.price
     *
     * @param price the value for t_order.price
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.orderrid
     *
     * @return the value of t_order.orderrid
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    public String getOrderrid() {
        return orderrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.orderrid
     *
     * @param orderrid the value for t_order.orderrid
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    public void setOrderrid(String orderrid) {
        this.orderrid = orderrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.tableid
     *
     * @return the value of t_order.tableid
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    public Integer getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.tableid
     *
     * @param tableid the value for t_order.tableid
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    public void setTableid(Integer tableid) {
        this.tableid = tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.mid
     *
     * @return the value of t_order.mid
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.mid
     *
     * @param mid the value for t_order.mid
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    public void setMid(String mid) {
        this.mid = mid;
    }
}