package com.ygy.model;

public class TOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.o_id
     *
     * @mbggenerated Mon May 20 16:59:04 CST 2019
     */
    private String oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.json
     *
     * @mbggenerated Mon May 20 16:59:04 CST 2019
     */
    private String json;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.o_id
     *
     * @return the value of t_order.o_id
     *
     * @mbggenerated Mon May 20 16:59:04 CST 2019
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.o_id
     *
     * @param oId the value for t_order.o_id
     *
     * @mbggenerated Mon May 20 16:59:04 CST 2019
     */
    public void setoId(String oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.json
     *
     * @return the value of t_order.json
     *
     * @mbggenerated Mon May 20 16:59:04 CST 2019
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.json
     *
     * @param json the value for t_order.json
     *
     * @mbggenerated Mon May 20 16:59:04 CST 2019
     */
    public void setJson(String json) {
        this.json = json;
    }
}