package com.ygy.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbggenerated Thu Apr 11 11:11:22 CST 2019
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pass
     *
     * @mbggenerated Thu Apr 11 11:11:22 CST 2019
     */
    private String pass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbggenerated Thu Apr 11 11:11:22 CST 2019
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbggenerated Thu Apr 11 11:11:22 CST 2019
     */
    public void setuId(String uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pass
     *
     * @return the value of user.pass
     *
     * @mbggenerated Thu Apr 11 11:11:22 CST 2019
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pass
     *
     * @param pass the value for user.pass
     *
     * @mbggenerated Thu Apr 11 11:11:22 CST 2019
     */
    public void setPass(String pass) {
        this.pass = pass;
    }
}