package com.ygy.mapper;

import com.ygy.model.Customer;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Mar 30 22:25:58 CST 2019
     */
    int insertSelective(Customer record);
    Customer select(int cid);
}