package com.ygy.mapper;

import com.ygy.model.Restaurant;

import javax.validation.constraints.Max;
import java.util.List;

public interface RestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    int deleteByPrimaryKey(String rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    int insert(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    int insertSelective(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    Restaurant selectByPrimaryKey(String rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    int updateByPrimaryKeySelective(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbggenerated Wed May 08 16:48:14 CST 2019
     */
    int updateByPrimaryKey(Restaurant record);

}