package com.ygy.mapper;

import com.ygy.model.TOrder;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    int deleteByPrimaryKey(String oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    int insert(TOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    int insertSelective(TOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    TOrder selectByPrimaryKey(String oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    int updateByPrimaryKeySelective(TOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Apr 10 10:35:27 CST 2019
     */
    int updateByPrimaryKey(TOrder record);
    /**
    * @Description:
    * @Param: [tableid]
    * @return: com.ygy.model.TOrder
    * @Author: ygy
    * @Date: 2019/4/10
    */
    TOrder selectByTableID(int tableid);
    /** 
    * @Description:
    * @Param: [tableid] 
    * @return: int 
    * @Author: ygy 
    * @Date: 2019/4/10 
    */ 
    int deletByTableID(int tableid);

}